steps:
  - name: "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/pipeline-executor"
    args:
      [
        "--name=yolov8-training-pipeline",
        "--pipeline_def=./yolov8-training-pipeline.yaml",
        "--pipeline_root=gs://tmp_data_engineering_assignment_group_7",
        "--parameter_dict=./parameters.json",
      ]
