steps:
  - name: "python:3.10"
    entrypoint: "python"
    args: ["--version"]

  # Install dependencies
  - name: "python:3.10"
    entrypoint: pip
    args:
      [
        "install",
        "--user",
        "--no-cache-dir",
        "--upgrade",
        "kfp>2",
        "google-cloud-pipeline-components>2",
        "google-cloud-aiplatform",
      ]

  # Compile pipeline
  - name: "python:3.10"
    entrypoint: "python"
    args: ["yolov8_training/training_pipeline_compiler/pipeline.py"]
    env:
      - "LOCATION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
      - "TAG_NAME=$TAG_NAME"

  # Upload compiled pipeline to GCS.
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "yolov8-training-pipeline.yaml",
        "gs://tmp_data_engineering_assignment_group_7",
      ]
