version: "3.9"

services:
  training:
    image: 'europe-west1-docker.pkg.dev/data-engineering-assignment-1/docker-image-repo/yolov8-training-image:tag1'
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '8gb'
    restart: always
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
