version: "3.9"

services:
  api:
    image: 'europe-west1-docker.pkg.dev/data-engineering-assignment-1/docker-image-repo/yolov8-api-image:tag1'
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '8gb'
    restart: always
    environment:
      POTREE_API_TOKEN: ${POTREE_API_TOKEN:?}
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
