version: "3.9"

services:
  api:
    image: "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8-image:${TAG_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '8gb'
    restart: always
    environment:
      POTREE_API_TOKEN: ${POTREE_API_TOKEN}
    ports:
      - "5000:5000"
    volumes:
      - api-volume:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  api-volume: