steps:
  # Download compiled pipeline from GCS.
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://tmp_data_engineering_assignment_group_7/yolov8-training-pipeline.yaml",
        ".",
      ]

  - name: "${LOCATION}-docker.pkg.dev/$PROJECT_ID/docker-image-repo/pipeline-executor:${TAG_NAME}"
    args:
      [
        "--name=yolov8-training-pipeline",
        "--pipeline_def=../yolov8-training-pipeline.yaml",
        "--pipeline_root=gs://tmp_data_engineering_assignment_group_7",
        "--parameter_dict=../parameters.json",
      ]
    env:
      - "REGION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
