#cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "app/docker-compose.yml", "build"]
    env:
      - "LOCATION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
      - "TAG_NAME=$TAG_NAME"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_trainer:${TAG_NAME}",
        "./yolov8_training/components/trainer",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_downloader:${TAG_NAME}",
        "./yolov8_training/components/downloader",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "app/docker-compose.yml", "push"]
    env:
      - "LOCATION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
      - "TAG_NAME=$TAG_NAME"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_trainer:${TAG_NAME}",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_downloader:${TAG_NAME}",
      ]

  - name: "bash"
    script: |
      #!/usr/bin/env bash
      sed -i s@%PREDICTION%@${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8-image:${TAG_NAME}@g ci-cd/service.yaml
      sed -i s@%API%@${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/prediction-ui:${TAG_NAME}@g ci-cd/service.yaml
      sed -i s@%API_URL%@${API_URL}@g ci-cd/service.yaml
      sed -i s@%POTREE_API_TOKEN%@${POTREE_API_TOKEN}@g ci-cd/service.yaml
    automapSubstitutions: true

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["run", "services", "replace", "ci-cd/service.yaml"]
