#cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "app/docker-compose.yml", "build"]
    env:
      - "LOCATION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
      - "TAG_NAME=$TAG_NAME"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_trainer:${TAG_NAME}",
        "./yolov8_training/components/trainer",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_downloader:${TAG_NAME}",
        "./yolov8_training/components/downloader",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "app/docker-compose.yml", "push"]
    env:
      - "LOCATION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
      - "TAG_NAME=$TAG_NAME"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_trainer:${TAG_NAME}",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8_downloader:${TAG_NAME}",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["run", "services", "replace", "ci-cd/service.yaml"]
    env:
      - "LOCATION=$LOCATION"
      - "PROJECT_ID=$PROJECT_ID"
      - "TAG_NAME=$TAG_NAME"
      - "POTREE_API_TOKEN=$_POTREE_API_TOKEN"
      - "API_URL=$_API_URL"
