apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: europe-west1
  name: app
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: '{"app":["api"]}'
    spec:
      containers:
        - image: "%PREDICTION%"
          name: app
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: POTREE_API_TOKEN
              value: "%POTREE_API_TOKEN%"
            - name: API_URL
              value: "%API_URL%"
        - image: "%API%"
          name: api
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: POTREE_API_TOKEN
              value: "%POTREE_API_TOKEN%"
