apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: europe-west1
  name: app
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: "europe-west1-docker.pkg.dev/data-engineering-assignment-1/docker-image-repo/prediction-ui:release-0.4.1"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: POTREE_API_TOKEN
              value: ${POTREE_API_TOKEN}
            - name: API_URL
              value: ${API_URL}
        - image: "europe-west1-docker.pkg.dev/data-engineering-assignment-1/docker-image-repo/yolov8-image:release-0.4.1"
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: POTREE_API_TOKEN
              value: ${POTREE_API_TOKEN}
