apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: europe-west1
  name: MLOps-app
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1 #or gen2
    spec:
      containers:
        - image: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/prediction-ui:${TAG_NAME}
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: POTREE_API_TOKEN
              value: ${_POTREE_API_TOKEN}
            - name: API_URL
              value: ${_API_URL}
        - image: "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker-image-repo/yolov8-image:${TAG_NAME}"
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: POTREE_API_TOKEN
              value: ${_POTREE_API_TOKEN}
